/* Edit the content objects below to update the site without changing the HTML. */
const churchData = {
  services: [
    { icon: '☀', title: 'Sunday First Service', time: '8:00 AM – 10:30 AM', detail: 'Worship, word & children\'s church' },
    { icon: '✦', title: 'Sunday Second Service', time: '11:00 AM – 1:00 PM', detail: 'Worship, word & community' },
    { icon: '◒', title: 'Tuesday & Friday Bible Study', time: '5:00 PM – 6:30 PM', detail: 'Go deeper in the Word together' }
  ],
  ministries: [
    { icon: '♧', title: 'Children', description: 'Big faith for little hearts, with joyful teaching and safe spaces to grow.' },
    { icon: '✦', title: 'Youth', description: 'A real community for the next generation to ask, create, and lead.' },
    { icon: '♡', title: 'Women', description: 'Friendship, prayer, and encouragement for every season of life.' },
    { icon: '♙', title: 'Men', description: 'Brotherhood that builds character, courage, and a life of purpose.' },
    { icon: '♫', title: 'Music & Choir', description: 'Use your voice and gifts to lead our church family in praise.' },
    { icon: '↗', title: 'Outreach', description: 'Taking the compassion of Jesus beyond our walls and into Mwatate.' }
  ],
  sermons: [
    { series: 'Sunday Series', title: 'The God Who Sees Me', speaker: 'Pastor Joseph Mwangi', date: '08 Sep 2026', link: '' },
    { series: 'Sunday Series', title: 'When Faith Gets Practical', speaker: 'Pastor Joseph Mwangi', date: '01 Sep 2026', link: 'https://youtu.be/IznIF3P_Hqw?si=o-b5swT3_q1UHxM-' },
    { series: 'Foundations', title: 'Built on the Rock', speaker: 'Rev. Mary Wambui', date: '25 Aug 2026', link: 'https://www.youtube.com/@JesusPalaceofPraise' },
    { series: 'Foundations', title: 'A People of Prayer', speaker: 'Pastor Joseph Mwangi', date: '18 Aug 2026', link: 'https://www.youtube.com/@JesusPalaceofPraise' },
    { series: 'Special Messages', title: 'Hope for Our Home', speaker: 'Rev. David Mwakio', date: '11 Aug 2026', link: 'https://www.youtube.com/@JesusPalaceofPraise' },
    { series: 'Special Messages', title: 'Praise in Every Season', speaker: 'Worship Team', date: '04 Aug 2026', link: 'https://www.youtube.com/@JesusPalaceofPraise' }
  ],
  events: [
    { date: '2026-10-04T08:00:00+03:00', day: '04', month: 'OCT', title: 'Harvest Thanksgiving Sunday', detail: 'Sunday · 8:00 AM & 11:00 AM', tag: 'Worship' },
    { date: '2026-10-16T17:00:00+03:00', day: '16', month: 'OCT', title: 'Youth Encounter Night', detail: 'Friday · 5:00 PM · Main sanctuary', tag: 'Youth' },
    { date: '2026-10-24T09:00:00+03:00', day: '24', month: 'OCT', title: 'Community Care Day', detail: 'Saturday · 9:00 AM · Mwatate Town', tag: 'Outreach' },
    { date: '2026-11-01T08:00:00+03:00', day: '01', month: 'NOV', title: 'Family Celebration Sunday', detail: 'Sunday · 8:00 AM & 11:00 AM', tag: 'Family' }
  ],
  leaders: [
    { name: 'Joseph Mwangi', role: 'Lead Pastor', image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=500&q=75' },
    { name: 'Mary Wambui', role: 'Associate Pastor', image: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&w=500&q=75' },
    { name: 'David Mwakio', role: 'Worship Pastor', image: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=500&q=75' },
    { name: 'Ruth Njeri', role: 'Community Director', image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=75' }
  ]
};

const translations = {
  en: { 'nav.about': 'About', 'nav.services': 'Services', 'nav.ministries': 'Ministries', 'nav.sermons': 'Sermons', 'nav.events': 'Events', 'nav.give': 'Give', 'nav.visit': 'Plan a visit', 'hero.eyebrow': 'WELCOME HOME · MWATATE, KENYA', 'hero.title': 'A House of Praise.', 'hero.copy': 'A warm family of faith where every generation can encounter Jesus, find belonging, and live with purpose.', 'hero.visit': 'Plan Your Visit →', 'hero.live': 'Watch Live ↗', 'hero.note': 'Sunday worship · In person & online', 'about.title': 'There is room for you here.', 'about.copy': 'Jesus Palace of Praise is a Pentecostal church family in the heart of Mwatate. We gather to lift up Jesus, care for one another, and take the good news beyond our walls.', 'about.link': 'Meet us this Sunday →', 'about.historyTitle': 'A simple beginning. A living hope.', 'about.history': 'Born from a desire to see Taita Taveta encounter the love of Christ, our church continues to grow as a place of prayer, worship, and practical community.', 'about.visionTitle': 'Our vision', 'about.missionTitle': 'Our mission', 'about.beliefsTitle': 'Our beliefs', 'about.vision': 'To see transformed lives and thriving communities through the hope of Jesus.', 'about.mission': 'Know Christ, grow together, and make a difference wherever God sends us.', 'about.beliefs': 'We are grounded in Scripture, led by the Spirit, and centered on the saving grace of Jesus.', 'services.title': 'Worship with us.', 'services.copy': 'Your seat is ready. Join us in Mwatate Town for a joyful, life-giving gathering.', 'services.directions': 'Get directions ↗', 'ministries.title': 'There is a place for everyone.', 'ministries.copy': 'Faith grows best in community. Find a circle where you can be known, encouraged, and equipped.', 'sermons.title': 'Words that stay with you.', 'sermons.copy': 'Catch up on the latest messages and carry a little more hope into your week.', 'events.title': 'What’s happening around here.', 'events.next': 'NEXT EVENT IN', 'giving.title': 'Your giving helps hope go further.', 'giving.copy': 'Every gift supports worship, discipleship, outreach, and care across our community. Thank you for building with us.', 'contact.title': 'Let’s connect.', 'contact.copy': 'Have a prayer request, a question, or need directions? Send us a message. Our team will get back to you soon.', 'contact.whatsapp': 'Chat on WhatsApp', 'leadership.title': 'Meet our leaders.', 'footer.copy': 'A House of Praise in Mwatate Town.' },
  sw: { 'nav.about': 'Kuhusu', 'nav.services': 'Ibada', 'nav.ministries': 'Huduma', 'nav.sermons': 'Mahubiri', 'nav.events': 'Matukio', 'nav.give': 'Toa', 'nav.visit': 'Panga ziara', 'hero.eyebrow': 'KARIBU NYUMBANI · MWATATE, KENYA', 'hero.title': 'Nyumba ya Sifa.', 'hero.copy': 'Familia yenye joto ya imani ambapo kila kizazi kinaweza kukutana na Yesu, kupata ushirika, na kuishi kwa kusudi.', 'hero.visit': 'Panga Ziara Yako →', 'hero.live': 'Tazama Mubashara ↗', 'hero.note': 'Ibada ya Jumapili · Kanisani na mtandaoni', 'about.title': 'Kuna nafasi yako hapa.', 'about.copy': 'Jesus Palace of Praise ni familia ya kanisa la Kipentekoste katikati ya Mwatate. Tunakusanyika kumtukuza Yesu, kutunza kila mmoja, na kupeleka habari njema nje ya kuta zetu.', 'about.link': 'Kutana nasi Jumapili hii →', 'about.historyTitle': 'Mwanzo rahisi. Tumaini hai.', 'about.history': 'Kanisa letu lilizaliwa kutokana na hamu ya kuona Taita Taveta ikikutana na upendo wa Kristo, na linaendelea kukua kama mahali pa maombi, ibada, na jamii.', 'about.visionTitle': 'Maono yetu', 'about.missionTitle': 'Dhamira yetu', 'about.beliefsTitle': 'Imani yetu', 'about.vision': 'Kuona maisha yakibadilika na jamii zikistawi kupitia tumaini la Yesu.', 'about.mission': 'Kumjua Kristo, kukua pamoja, na kuleta mabadiliko popote Mungu anapotutuma.', 'about.beliefs': 'Tumejengwa juu ya Maandiko, tunaongozwa na Roho, na tunamtegemea Yesu kwa wokovu.', 'services.title': 'Ibada pamoja nasi.', 'services.copy': 'Kiti chako kiko tayari. Jiunge nasi Mwatate Town kwa mkusanyiko wa furaha na uzima.', 'services.directions': 'Pata maelekezo ↗', 'ministries.title': 'Kuna nafasi kwa kila mtu.', 'ministries.copy': 'Imani hukua vizuri katika jamii. Tafuta kundi ambako utajulikana, kutiwa moyo, na kuwezeshwa.', 'sermons.title': 'Maneno yatakayobaki nawe.', 'sermons.copy': 'Sikiliza ujumbe wa hivi karibuni na ubebe tumaini zaidi katika wiki yako.', 'events.title': 'Kinachoendelea hapa.', 'events.next': 'TUKIO LIJALO KWA', 'giving.title': 'Ukarimu wako hupeleka tumaini mbali.', 'giving.copy': 'Kila zawadi inasaidia ibada, ufuasi, huduma, na utunzaji katika jamii yetu. Asante kwa kujenga nasi.', 'contact.title': 'Tuungane.', 'contact.copy': 'Una ombi la maombi, swali, au unahitaji maelekezo? Tutumie ujumbe. Timu yetu itakujibu hivi karibuni.', 'contact.whatsapp': 'Ongea nasi WhatsApp', 'leadership.title': 'Kutana na viongozi wetu.', 'footer.copy': 'Nyumba ya Sifa huko Mwatate Town.' }
};

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));

function renderServices() { $('#service-list').innerHTML = churchData.services.map((service) => `<article class="service-card reveal"><span class="service-icon" aria-hidden="true">${service.icon}</span><div><h3>${escapeHtml(service.title)}</h3><p><strong>${escapeHtml(service.time)}</strong><br>${escapeHtml(service.detail)}</p></div></article>`).join(''); }
function renderMinistries() { $('#ministry-grid').innerHTML = churchData.ministries.map((ministry) => `<article class="ministry-card reveal"><span class="ministry-icon" aria-hidden="true">${ministry.icon}</span><h3>${escapeHtml(ministry.title)}</h3><p>${escapeHtml(ministry.description)}</p></article>`).join(''); }
function renderSermons() {
  const query = ($('#sermon-search').value || '').toLowerCase();
  const series = $('#series-filter').value;
  const results = churchData.sermons.filter((sermon) => (series === 'all' || sermon.series === series) && `${sermon.title} ${sermon.speaker} ${sermon.series}`.toLowerCase().includes(query));
  $('#sermon-grid').innerHTML = results.length ? results.map((sermon) => `<article class="sermon-card reveal"><div class="sermon-art"><small>${escapeHtml(sermon.series)}</small><span aria-hidden="true">▶</span></div><div class="sermon-card-content"><h3>${escapeHtml(sermon.title)}</h3><p>${escapeHtml(sermon.speaker)} · ${escapeHtml(sermon.date)}</p><a class="sermon-link" href="${sermon.link}" target="_blank" rel="noopener">Watch message ↗</a></div></article>`).join('') : '<p class="empty-state">No sermons match your search.</p>';
  observeReveals();
}
function renderEvents() { $('#events-list').innerHTML = churchData.events.map((event) => `<article class="event-row reveal"><div class="date-badge"><strong>${event.day}</strong><small>${event.month}</small></div><div><h3>${escapeHtml(event.title)}</h3><p>${escapeHtml(event.detail)}</p></div><span class="event-tag">${escapeHtml(event.tag)}</span></article>`).join(''); }
function renderLeaders() { $('#leadership-grid').innerHTML = churchData.leaders.map((leader) => `<article class="leader-card reveal"><img src="${leader.image}" loading="lazy" alt="Placeholder portrait of ${escapeHtml(leader.name)} - replace with church photo"><div class="leader-info"><h3>${escapeHtml(leader.name)}</h3><p>${escapeHtml(leader.role)}</p></div></article>`).join(''); }
function populateSeries() { [...new Set(churchData.sermons.map((sermon) => sermon.series))].forEach((series) => $('#series-filter').insertAdjacentHTML('beforeend', `<option value="${escapeHtml(series)}">${escapeHtml(series)}</option>`)); }
function observeReveals() { const elements = $$('.reveal:not(.observed)'); if (!('IntersectionObserver' in window)) { elements.forEach((element) => element.classList.add('visible')); return; } const observer = new IntersectionObserver((entries, currentObserver) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('visible'); currentObserver.unobserve(entry.target); } }), { threshold: .12 }); elements.forEach((element) => { element.classList.add('observed'); observer.observe(element); }); }
function updateCountdown() { const next = churchData.events.map((event) => ({ ...event, timestamp: new Date(event.date).getTime() })).find((event) => event.timestamp > Date.now()); if (!next) { $('#countdown').textContent = 'See you soon'; return; } const distance = next.timestamp - Date.now(); const days = Math.floor(distance / 86400000); const hours = Math.floor((distance % 86400000) / 3600000); const minutes = Math.floor((distance % 3600000) / 60000); $('#countdown').textContent = `${days}d ${hours}h ${minutes}m`; }
function applyLanguage(language) { document.documentElement.lang = language; $$('[data-i18n]').forEach((element) => { const value = translations[language][element.dataset.i18n]; if (value) element.textContent = value; }); localStorage.setItem('jpop-language', language); $('#language-toggle').textContent = language === 'en' ? 'SW' : 'EN'; }

renderServices(); renderMinistries(); renderSermons(); renderEvents(); renderLeaders(); populateSeries(); observeReveals(); updateCountdown(); setInterval(updateCountdown, 60000);

$('#sermon-search').addEventListener('input', renderSermons); $('#series-filter').addEventListener('change', renderSermons);
$('#language-toggle').addEventListener('click', () => applyLanguage(document.documentElement.lang === 'en' ? 'sw' : 'en'));
const savedLanguage = localStorage.getItem('jpop-language'); if (savedLanguage === 'sw') applyLanguage('sw');
const savedTheme = localStorage.getItem('jpop-theme'); if (savedTheme === 'dark') document.body.classList.add('dark');
$('#theme-toggle').addEventListener('click', () => { document.body.classList.toggle('dark'); localStorage.setItem('jpop-theme', document.body.classList.contains('dark') ? 'dark' : 'light'); });
$$('.copy-button').forEach((button) => button.addEventListener('click', async () => { try { await navigator.clipboard.writeText(button.dataset.copy); $('.copy-feedback').textContent = `Copied ${button.dataset.copy} to clipboard.`; } catch { $('.copy-feedback').textContent = `Number: ${button.dataset.copy}`; } }));
$('#contact-form').addEventListener('submit', (event) => { event.preventDefault(); const form = event.currentTarget; const message = $('#form-message'); if (!form.checkValidity()) { message.textContent = 'Please complete each field before sending.'; message.className = 'form-message error'; form.reportValidity(); return; } message.textContent = 'Thank you. Your message is ready for the church team to respond to.'; message.className = 'form-message success'; form.reset(); });
const header = $('#site-header'); window.addEventListener('scroll', () => header.classList.toggle('scrolled', window.scrollY > 20), { passive: true });
const menuToggle = $('.menu-toggle'); const menu = $('#primary-menu'); menuToggle.addEventListener('click', () => { const open = menu.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', open); }); $$('.nav-menu a').forEach((link) => link.addEventListener('click', () => { menu.classList.remove('open'); menuToggle.setAttribute('aria-expanded', 'false'); }));
$('#year').textContent = new Date().getFullYear();
